name: vulnerability-scan-automation
on: [ push ]
jobs:
  release-process:
    name: Vulnerability Scan Automation
    runs-on: ubuntu-latest
    env:
      DOT_CICD_BRANCH: 20088-automated-vulnerability-scan
      DOCKER_BRANCH: 19756-docker-java-11
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: dotcmsbuild
      GITHUB_USER_TOKEN: ${{ secrets.USER_TOKEN }}
      PULL_REQUEST: ${{ github.event.number }}
      DEBUG: true
    steps:
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        if: env.DEBUG == 'true'
      - name: Get commit message
        id: get-commit-message
        uses: dotcms/get-commit-message@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Common Vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CURRENT_BRANCH="${{ github.head_ref }}"
          else
            CURRENT_BRANCH=$(basename "${{ github.ref }}")
          fi

          COMMIT_MESSG="${{ steps.get-commit-message.outputs.commit_message }}"
          echo "COMMIT_MESSG: ${COMMIT_MESSG}"
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV
      - name: Prepare dot-cicd
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/dotCMS/dot-cicd/${DOT_CICD_BRANCH}/seed/install-dot-cicd.sh)"
      - name: Run Vulnerabily Scan
        run: |
          ../dotcicd/library/pipeline.sh runSidecar scan
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
          CUSTOM_STARTER_URL: "https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20210312/starter-20210312.zip"
